### ISSUE TITLE
Close connections

### ISSUE THREAD

**Issue by edvorg** [kumarshantanu/clj-dbcp#3]
Hi, is it possible to close ALL connections to the db?
I tried closing datasource, connection from data source, nothing help me.

**Comment by kumarshantanu** [comment]
Calling `(.close ^org.apache.commons.dbcp.BasicDataSource ds)` will ensure no new connections can be obtained from the pool. Active connections must be closed by your program. Suggestions welcome on how to implement this feature request.

**Comment by kumarshantanu** [comment]
Closing this issue as no feedback/contribution has been submitted in quite some time.
